"""initial schema

Revision ID: 77d08bef589b
Revises: 
Create Date: 2026-08-28 07:30:00.841734
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types (GUID, UTCDateTime) are rendered with their full module
# path by autogenerate, so this import must be present in every revision.
import app.core.database



revision: str = '77d08bef589b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_catalog',
    sa.Column('food_key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('display_name_te', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('energy_kcal_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_g_per_100g', sa.Float(), nullable=True),
    sa.Column('carbohydrate_g_per_100g', sa.Float(), nullable=True),
    sa.Column('fat_g_per_100g', sa.Float(), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_catalog')),
    sa.UniqueConstraint('food_key', name='uq_food_catalog_food_key')
    )
    with op.batch_alter_table('food_catalog', schema=None) as batch_op:
        batch_op.create_index('ix_food_catalog_category', ['category'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('uq_users_active_email', ['email'], unique=True, postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = 0'))

    op.create_table('audit_events',
    sa.Column('user_id', app.core.database.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('client_hint', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_events_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('food_densities',
    sa.Column('food_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('density_g_per_ml', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_version', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_food_densities_confidence_is_probability')),
    sa.CheckConstraint('density_g_per_ml > 0 AND density_g_per_ml < 3', name=op.f('ck_food_densities_density_is_plausible')),
    sa.ForeignKeyConstraint(['food_id'], ['food_catalog.id'], name=op.f('fk_food_densities_food_id_food_catalog'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_densities')),
    sa.UniqueConstraint('food_id', 'source', 'source_version', name='uq_food_densities_source')
    )
    with op.batch_alter_table('food_densities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_densities_food_id'), ['food_id'], unique=False)

    op.create_table('meals',
    sa.Column('user_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('consumed_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_mass_g', sa.Float(), nullable=True),
    sa.Column('total_energy_kcal', sa.Float(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('client_recorded_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.CheckConstraint('total_mass_g IS NULL OR total_mass_g >= 0', name=op.f('ck_meals_total_mass_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_meals_user_idempotency_key')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_meals_user_active_consumed', ['user_id', 'is_deleted', 'consumed_at'], unique=False)
        batch_op.create_index('ix_meals_user_consumed_at', ['user_id', 'consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_fingerprint', name='uq_refresh_tokens_token_fingerprint')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_tokens_user_active', ['user_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('sync_queue',
    sa.Column('user_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', app.core.database.GUID(length=36), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('completed_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_queue_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_queue')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_sync_queue_user_idempotency')
    )
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.create_index('ix_sync_queue_user_state', ['user_id', 'state'], unique=False)

    op.create_table('ai_predictions',
    sa.Column('meal_id', app.core.database.GUID(length=36), nullable=True),
    sa.Column('user_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=False),
    sa.Column('raw_output_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('image_sha256', sa.String(length=64), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('processing_ms >= 0', name=op.f('ck_ai_predictions_processing_ms_non_negative')),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_ai_predictions_meal_id_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_predictions'))
    )
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.create_index('ix_ai_predictions_engine_version', ['engine', 'model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_predictions_image_sha256'), ['image_sha256'], unique=False)
        batch_op.create_index('ix_ai_predictions_meal', ['meal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_predictions_user_id'), ['user_id'], unique=False)

    op.create_table('meal_images',
    sa.Column('meal_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.CheckConstraint('byte_size > 0', name=op.f('ck_meal_images_byte_size_positive')),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_images_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_images')),
    sa.UniqueConstraint('content_sha256', 'meal_id', name='uq_meal_images_content_meal')
    )
    with op.batch_alter_table('meal_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_images_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_images_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_meal_images_meal', ['meal_id'], unique=False)

    op.create_table('meal_items',
    sa.Column('meal_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('food_key', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('estimated_volume_ml', sa.Float(), nullable=False),
    sa.Column('estimated_mass_g', sa.Float(), nullable=False),
    sa.Column('density_g_per_ml', sa.Float(), nullable=False),
    sa.Column('density_source', sa.String(length=120), nullable=False),
    sa.Column('recognition_confidence', sa.Float(), nullable=False),
    sa.Column('portion_confidence', sa.Float(), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbohydrate_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('was_user_corrected', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('original_mass_g', sa.Float(), nullable=True),
    sa.Column('original_display_name', sa.String(length=160), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.CheckConstraint('estimated_mass_g > 0', name=op.f('ck_meal_items_mass_positive')),
    sa.CheckConstraint('estimated_volume_ml > 0', name=op.f('ck_meal_items_volume_positive')),
    sa.CheckConstraint('portion_confidence >= 0 AND portion_confidence <= 1', name=op.f('ck_meal_items_portion_confidence_is_probability')),
    sa.CheckConstraint('recognition_confidence >= 0 AND recognition_confidence <= 1', name=op.f('ck_meal_items_recognition_confidence_is_probability')),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_items_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items'))
    )
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_items_food_key'), ['food_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_meal_items_meal', ['meal_id'], unique=False)

    op.create_table('portion_estimates',
    sa.Column('meal_item_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('volume_ml', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=48), nullable=False),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_portion_estimates_confidence_is_probability')),
    sa.CheckConstraint('volume_ml > 0', name=op.f('ck_portion_estimates_volume_positive')),
    sa.ForeignKeyConstraint(['meal_item_id'], ['meal_items.id'], name=op.f('fk_portion_estimates_meal_item_id_meal_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portion_estimates'))
    )
    with op.batch_alter_table('portion_estimates', schema=None) as batch_op:
        batch_op.create_index('ix_portion_estimates_item', ['meal_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portion_estimates', schema=None) as batch_op:
        batch_op.drop_index('ix_portion_estimates_item')

    op.drop_table('portion_estimates')
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.drop_index('ix_meal_items_meal')
        batch_op.drop_index(batch_op.f('ix_meal_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meal_items_food_key'))

    op.drop_table('meal_items')
    with op.batch_alter_table('meal_images', schema=None) as batch_op:
        batch_op.drop_index('ix_meal_images_meal')
        batch_op.drop_index(batch_op.f('ix_meal_images_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meal_images_content_sha256'))

    op.drop_table('meal_images')
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_predictions_user_id'))
        batch_op.drop_index('ix_ai_predictions_meal')
        batch_op.drop_index(batch_op.f('ix_ai_predictions_image_sha256'))
        batch_op.drop_index('ix_ai_predictions_engine_version')

    op.drop_table('ai_predictions')
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_queue_user_state')

    op.drop_table('sync_queue')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index('ix_refresh_tokens_user_active')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_user_id'))
        batch_op.drop_index('ix_meals_user_consumed_at')
        batch_op.drop_index('ix_meals_user_active_consumed')
        batch_op.drop_index(batch_op.f('ix_meals_is_deleted'))

    op.drop_table('meals')
    with op.batch_alter_table('food_densities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_densities_food_id'))

    op.drop_table('food_densities')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_user_created')
        batch_op.drop_index('ix_audit_events_action')

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_active_email', postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = 0'))
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    with op.batch_alter_table('food_catalog', schema=None) as batch_op:
        batch_op.drop_index('ix_food_catalog_category')

    op.drop_table('food_catalog')
    # ### end Alembic commands ###
